### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by daxpedda** [ScanMountGoat/wgsl_to_wgpu#14]
Setting up CI would be great!
Happy to make a PR with the following:
- Check build
- Run tests
- Build examples
- Clippy
- Rustfmt
- RustSec
- Dependabot (technically not CI, but while I would be at it)

**Comment by ScanMountGoat** [comment]
CI isn't a big priority at the moment since there isn't a large number of commits and PRs to review. I may consider this in the future if the project becomes bigger and less experimental.
