### ISSUE TITLE
Switch to `quote` and use `prettyplease`

### ISSUE THREAD

**Issue by daxpedda** [ScanMountGoat/wgsl_to_wgpu#16]
I think it would be a good additions to use `quote` instead of writing code into unchecked strings. It also alleviates the effort of having to format the code by hand, as [`prettyplease`](https://crates.io/crates/prettyplease) can do that for us.

From a dependency perspective there isn't any difference. `naga` already pulls in `syn` & co and `prettyplease` uses the same dependencies.

Happy to do a PR upon green-lighting.

**Comment by ScanMountGoat** [comment]
I used quote initially but wasn't aware of prettyplease. It should be pretty straightforward for me to port the old code over.

**Comment by daxpedda** [comment]
`prettyplease` take a [`syn::File`](https://docs.rs/syn/1.0.98/syn/struct.File.html), so there is some additional work that needs to be done, but yeah, should all be pretty straightforward!
