### ISSUE TITLE
Generate function that returns VertexBufferLayout for types

### ISSUE THREAD

**Issue by badicsalex** [ScanMountGoat/wgsl_to_wgpu#24]
First of all, I love this crate, it cuts down on the boiler plate so much.

I have a small feature request:
there could be a function that returns a complete `VertexBufferLayout` for the generated types, and not just the attributes. It's somewhat repetitive to always create that struct instead of just calling a function a'la the [`Vertex::desc()` function](https://sotrh.github.io/learn-wgpu/beginner/tutorial4-buffer/#so-what-do-i-do-with-it) in the `wgpu` tutorial.

Maybe the `step_mode` could be a parameter.

**Comment by ScanMountGoat** [comment]
Glad you're enjoying it. It makes maintaining large uber shaders in my projects substantially less tedious. This would be a nice feature, but correctly calculating the size of the struct in WGSL for the array_stride will be a challenge. Using `std::mem::size_of::<Vertex>` won't work if Rust lays out the struct differently than WGSL expects. I could just derive `encase`, but that won't work on `glam` types. The second challenge is checking if the Rust struct layout actually matches the expected WGSL layout. This could also be solved by deriving encase.

The goal is to avoid generating incorrect code that might stump beginners. One solution might be to just generate this code when using encase.
https://crates.io/crates/encase
https://gpuweb.github.io/gpuweb/wgsl/#memory-layouts

**Comment by ScanMountGoat** [comment]
It looks like `encase` has feature flags for `glam`, `mint`, etc. That's probably the safest option instead of making assumptions about the size.

**Comment by badicsalex** [comment]
>Using std::mem::size_of::<Vertex> won't work if Rust lays out the struct differently than WGSL expects
I'm not sure I understand the problem for the Vertex Buffer case. The stride should match the array element size on the API caller side, so that will be by definition what WGSL "expects". Same with the struct layout: that's told to `wgpu` through the vertex attributes.
The problem is way bigger with uniform buffer fields, of course.

In Rust, arrays are [guaranteed to be densely packed](https://doc.rust-lang.org/reference/type-layout.html#array-layout), and struct size is [always a multiple of the alignment](https://doc.rust-lang.org/reference/type-layout.html#reprc-structs) (which in turn is at least as much as the most aligned field). This means `std::mem::size_of::<Vertex>` is the correct solution, and not just by accident.

The only error I can think of is if `wgpu` does not like the alignment of the stride, but you should get a pretty loud error for that.

BTW, I have already gotten some build failures with `glam::Vec3` and `bytemuck`'s padding policy ( related: #8 ), so I'm probably going to switch to `encase` as well.

**Comment by badicsalex** [comment]
Fun fact, I just tried the following shader:
```wgsl
struct Vertex {
    @location(0) position: vec3<f32>,
    @location(1) color: vec4<f32>,
};
```

Which generated:
```
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, bytemuck::Pod, bytemuck::Zeroable)]
pub struct Vertex {
    pub position: [f32; 3],
    pub color: [f32; 4],
}
```

Importantly, size is 28, and the offset of the second field is 12. That should have been an error, because Vec4<f32> should be aligned to 16 bytes. But it actually works on my computer (I guess no check in `wgpu`, and the nvidia driver is lenient)

What doesn't work is if I use `glam` types for the same code. First, the offset remains 12,  which is wrong, because `glam::Vec4` is 16-aligned (at least on my computer, as it is compiled to the `_m128` SIMD type). This is an issue with using the `wgpu::vertex_attr_array!` macro, which is not "glam-aware".

Second, as above, `bytemuck` complains about undefined padding bytes.

But interestingly, `mem::size` is correct, and so is the stride, so if I manually fill the offsets, and not use bytemuck, everything works again.

I didn't report these separately because using `vec3` makes no sense (you don't actually save memory bandwidth due to the alignment) and I just rounded everything up to vec4.

**Comment by ScanMountGoat** [comment]
> In Rust, arrays are [guaranteed to be densely packed](https://doc.rust-lang.org/reference/type-layout.html#array-layout), and struct size is [always a multiple of the alignment](https://doc.rust-lang.org/reference/type-layout.html#reprc-structs) (which in turn is at least as much as the most aligned field). This means `std::mem::size_of::<Vertex>` is the correct solution, and not just by accident.

This sounds correct for using bytemuck on a slice of `Vertex`.

> But interestingly, `mem::size` is correct, and so is the stride, so if I manually fill the offsets, and not use bytemuck, everything works again.

Using `vertex_attr_array!` assumes the struct members are tightly packed and is probably a bad idea. I would need to calculate the field offsets manually. I'll need to do some more reading on the WebGPU spec for [requirements on the vertex buffer layout](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuvertexbufferlayout) to see if it's compatible with the`repr(C)` layout.

**Comment by ScanMountGoat** [comment]
> Importantly, size is 28, and the offset of the second field is 12. That should have been an error, because Vec4 should be aligned to 16 bytes. But it actually works on my computer (I guess no check in `wgpu`, and the nvidia driver is lenient)

After doing some digging, it looks like this restriction exists on [WebGL and OpenGL ES](https://github.com/KhronosGroup/WebGL/issues/914).  This restriction also exists on [WebGPU](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuvertexbufferlayout) likely to maintain compatibility. I couldn't find any code in wgpu that enforces this, however. Bevy engine seems to be [using vec3 for some attributes](https://github.com/bevyengine/bevy/blob/e71c4d280294aba2ad494443170790dfba67ba03/crates/bevy_render/src/mesh/mesh/mod.rs#L59-L69) and [manually generating a tightly packed vertex buffer](https://github.com/bevyengine/bevy/blob/e71c4d280294aba2ad494443170790dfba67ba03/crates/bevy_render/src/mesh/mesh/mod.rs#L257-L283).

I've added a `vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout` function that gets the offsets and stride from the Rust struct instead of using the `vertex_attr_array!` macro. There are still some alignment issues to work through, but those fall under #8.
