### ISSUE TITLE
Adding support for deriving serde Serialize and Deserialize on generated structs.

### ISSUE THREAD

**Issue by slackers123** [ScanMountGoat/wgsl_to_wgpu#32]
Adding this would be helpful when trying to use the generated output of wgsl_to_wgpu as the types for a whole project.
I will try adding this in my own fork since it seems fairly simple.

Thank you for this amazing crate, and I hope my contribution is helpful.

**Comment by ScanMountGoat** [comment]
This could be a neat feature but should definitely be optional. You could add a `derive_serde` field to `WriteOptions` that defaults to false. This should be fairly simple to implement since a lot of the logic is already there for deriving bytemuck or encase.
