### ISSUE TITLE
Don't assume that all textures are filterable

### ISSUE THREAD

**Issue by badicsalex** [ScanMountGoat/wgsl_to_wgpu#37]
I've ran into this lovely TODO:

https://github.com/ScanMountGoat/wgsl_to_wgpu/blob/f85c08237e89d6547822b86a1f116322f5238418/wgsl_to_wgpu/src/bindgroup.rs#L192-L194

I'm trying to use R32Float texture views in a compute shader (with a `Nearest` filter in the sampler), but this code path does not let me. Unfortunately it's not clear at all how this could be made better, since there is no standard way of marking a texture non-filterable in WGSL.

I'd rather not fall back to manually altering bind group descriptors and creating bind groups.

**Comment by ScanMountGoat** [comment]
This is definitely something I'd like to address if possible. How are you declaring the texture in the compute shader? Is there a specific error you get with wgpu with filterable set to true? 

I've used R32Float textures in compute shaders in one of my projects for generating mipmaps from a depth texture. I use either something like `texture_storage_2d<r32float, read>` or `texture_2d<f32>`. This is all with `textureLoad` in WGSL and no samplers, however. I would need to review the spec to see whether the filterable field is something we can handle in wgsl_to_wgpu. If I recall, there are also some limitations in APIs like vulkan on which texture formats are filterable.

**Comment by badicsalex** [comment]
My declaration in wgsl is `texture_2d<f32>`. I get the following error when I try to bind an R32Float (instead of e.g. an R8Unorm):

```
    In Device::create_bind_group
    Texture binding 2 expects sample type = Float { filterable: true }, but given a view with format = R32Float
```

Using `textureLoad` with a `texture_storage_2d<r32float, read>` sounds like a solution actually, but for some reason it's not listed as an allowed combination on the [w3.org](https://www.w3.org/TR/WGSL/#textureload) site.

Then again, I might just switch to storage buffers. I have only one use-case where I need texture-like (i.e. non-linear) access pattern, but I also need filtering there.

>limitations in APIs like vulkan on which texture formats are filterable
R32Float is not filterable, but you can still sample it with a non-filtering sampler.

**Comment by ScanMountGoat** [comment]
> My declaration in wgsl is `texture_2d<f32>`. I get the following error when I try to bind an R32Float (instead of e.g. an R8Unorm):

I was trying to figure out why I couldn't reproduce this and then realized I had `Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES` enabled. If you're fine with native only, this is probably the best option for now. This also makes me wonder if the filterable field is even something I can determine at build time if users can potentially have this feature enabled.

**Comment by badicsalex** [comment]
Yeah, it probably cannot be determined at build time, it has to be a parameter or something.

Also, the samplers are also all market Filtering, when in fact not all samplers are.

>TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES

This is going to be my solution too, especially since I'm already native-only because of using storage textures in the compute pass. Thanks for the tip.

**Comment by badicsalex** [comment]
I think this can be closed as "not planned", I'm happy with this workaround.

**Comment by ScanMountGoat** [comment]
I've updated the limitations on the readme since this doesn't seem like something we can fix.
