### ISSUE TITLE
iterate through bind_groups

### ISSUE THREAD

**Issue by warriormaster12** [ScanMountGoat/wgsl_to_wgpu#46]
Is it possibel with current implementation to somehow loop through bind_groups when binding buffers to them? Atm I have a hard time figuring out how to avoid doing manually BindingGroup0, BindingGroup1 etc.

**Comment by ScanMountGoat** [comment]
Can you provide an example in code or pseudocode showing what you mean by looping? The current implementation supports setting the bind groups all at once with `set_bind_groups` or by manually calling `set(render_pass)` on each one.

**Comment by warriormaster12** [comment]
Sure, here's my pseudo code 

``` Rust
for bind_group in binding_groups: 
        bind_group.from_bindings(
            &context.device,
            bind_group.layout {
                buffer: buffer.as_entire_buffer_binding(),
            }
```
About something like this.

**Comment by ScanMountGoat** [comment]
Is this the code you're trying to simplify? 
https://github.com/warriormaster12/wgpu-engine/blob/ec43c0b28c5b332f30c15c421e2d8901a93e483e/src/renderer/context.rs#L61-L87

It looks like you're already creating and setting the bind groups correctly. Each bind group is a field in the `BindGroups` type in the struct to ensure that you remember to initialize it and use the right type of data. There are limits on the number of bind groups, so you should only ever have a few fields to set.
```python
# pseudocode
for mesh in meshes:
    set_bind_groups(camera_bind_group, mesh.material.bind_group)
    mesh.draw(pass)
```

What I described above isn't always the most efficient or convenient way to do it, but it does have the most compile time checks. In practice, you may want to set bind groups for different update frequencies. The global data like a camera would be bind group 0, the per model data would be bind group 1, etc. In this case, you would store the bind group types wherever it makes sense and set them explicitly with `bind_group.set(render_pass)`.  The camera data probably won't be stored in each mesh, for example. You can still use `set_bind_groups` in this case if you're willing to live with redundant bindings.
```python
# pseudocode
camera_bind_group.set(pass)
for mesh in meshes:
    mesh.material.bind_group.set(pass)
    mesh.draw(pass)
```
https://vkguide.dev/docs/chapter-4/descriptors/#mental-model

**Comment by ScanMountGoat** [comment]
I'll try and update the documentation to make this a bit clearer. There are still some limitations with the current generated code in regards to bind groups. Let me know if this resolves your issue or if you have any suggestions for ways to make the generated code more helpful.

**Comment by warriormaster12** [comment]
Fair enough, I guess I had a flaw in my thinking process. Though now I'm wondering how should I go about handling multiple shader files. Is it possible for the library to detect which bind_groups are the same in the build process?

**Comment by ScanMountGoat** [comment]
> Is it possible for the library to detect which bind_groups are the same in the build process?

Can you give a bit more detail on how you want to structure the WGSL files? You can add multiple entry points to the same program if all the bind groups are exactly the same, but this isn't always practical.

You can generate a different Rust module for each of your WGSL files. If you want to use multiple WGSL files in the same program, you'll need to combine them yourself before passing them to wgsl_to_wgpu. 

There's a limitation in the current code where you can't share types between programs when using the generated code (see #40). The types `shader1::Camera` and `shader2::Camera` aren't identical since they live in different modules. You can still set the bind groups yourself manually and rely on wgpu's runtime checking.

**Comment by ScanMountGoat** [comment]
Closing this as the initial issue has been resolved and the others are already issues.
