### ISSUE TITLE
Support pipeline overridable constants

### ISSUE THREAD

**Issue by stefnotch** [ScanMountGoat/wgsl_to_wgpu#58]
wgpu now supports constants that can be set when the pipeline is created https://github.com/gfx-rs/wgpu/releases/tag/v0.20.0

It'd be cool if those were supported in a type-safe way.

**Comment by ScanMountGoat** [comment]
This makes sense to just add as a struct parameter similar to javascript. I'll look into adding this to the example project.
https://www.w3.org/TR/webgpu/#dom-gpuprogrammablestage-constants

```rust
shader::Constants {
    _1300: 2.0,  // "gain"
    depth: -1.0,  // "depth"
}
```

**Comment by ScanMountGoat** [comment]
If you need to use pipeline-overrideable constants in your project, you can use the latest commit and reference the example project code. I still need to update the generated code to make it easier to actually set the constants in the compilation options.

**Comment by stefnotch** [comment]
That's amazing, thank you very much! I'll look at the examples and use that for now.

And I'll look forward to the codegen improvements.
